In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [6]:
matrix = np. array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
matrix                   

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a[0]

1

In [10]:
print('a    == {}'.format(a))
print('a[0] == {}'.format(a[0]))
print('a[1] == {}'.format(a[1]))
print('a[2] == {}'.format(a[2]))


a    == [1 2 3]
a[0] == 1
a[1] == 2
a[2] == 3


In [11]:
matrix[1, 1]

5

In [12]:
matrix[1:, :2]

array([[4, 5],
       [7, 8]])

In [13]:
should_include_elements = [True, False, True]
a[should_include_elements]

array([1, 3])

In [14]:
original_array = [1, 2, 3, 4, 5]
try:
    original_array + 1
except TypeError as e:
    print('An Error Occured!')
    print(f'TypeError: {e}')

An Error Occured!
TypeError: can only concatenate list (not "int") to list


In [15]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = []
for n in original_array:
    array_with_one_added.append(n + 1)
print(array_with_one_added)

[2, 3, 4, 5, 6]


In [16]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = [n + 1 for n in original_array]
print(array_with_one_added)

[2, 3, 4, 5, 6]


In [17]:
original_array = np.array([1, 2, 3, 4, 5])
original_array + 1

array([2, 3, 4, 5, 6])

In [19]:
my_array = np.array([-3, 0, 3, 16])
print('my_array      == {}'.format(my_array))
print('my_array - 5  == {}'.format(my_array - 5))
print('my_array * 4  == {}'.format(my_array * 4))
print('my_array / 2  == {}'.format(my_array / 2))
print('my_array ** 2 == {}'.format(my_array ** 2))
print('my_array % 2  == {}'.format(my_array % 2))

my_array      == [-3  0  3 16]
my_array - 5  == [-8 -5 -2 11]
my_array * 4  == [-12   0  12  64]
my_array / 2  == [-1.5  0.   1.5  8. ]
my_array ** 2 == [  9   0   9 256]
my_array % 2  == [1 0 1 0]


In [21]:
my_array = np.array([-3, 0, 3, 16])
print('my_array       == {}'.format(my_array))
print('my_array == -3 == {}'.format(my_array == -3))
print('my_array >= 0  == {}'.format(my_array >= 0))
print('my_array < 10  == {}'.format(my_array < 10))

my_array       == [-3  0  3 16]
my_array == -3 == [ True False False False]
my_array >= 0  == [False  True  True  True]
my_array < 10  == [ True  True  True False]


In [23]:
my_array[my_array > 0]

array([ 3, 16])

In [24]:
my_array[my_array % 2 == 0]

array([ 0, 16])

In [25]:
my_array % 2

array([1, 0, 1, 0])

In [26]:
result = my_array % 2
result == 0

array([False,  True, False,  True])

In [27]:
step_1 = my_array % 2
step_2 = step_1 == 0
step_3 = my_array[step_2]

step_3

array([ 0, 16])

In [28]:
print('1. my_array[my_array % 2 == 0]')
print('    - the original expression')
print('2. my_array[{} % 2 == 0]'.format(my_array))
print('    - variable substitution')
print('3. my_array[{} == 0]'.format(my_array % 2))
print('    - result of performing the vectorized modulus 2')
print('4. my_array[{}]'.format(my_array % 2 == 0))
print('    - result of comparing to 0')
print('5. {}[{}]'.format(my_array, my_array % 2 == 0))
print('    - variable substitution')
print('6. {}'.format(my_array[my_array % 2 == 0]))
print('    - our final result')

1. my_array[my_array % 2 == 0]
    - the original expression
2. my_array[[-3  0  3 16] % 2 == 0]
    - variable substitution
3. my_array[[1 0 1 0] == 0]
    - result of performing the vectorized modulus 2
4. my_array[[False  True False  True]]
    - result of comparing to 0
5. [-3  0  3 16][[False  True False  True]]
    - variable substitution
6. [ 0 16]
    - our final result


In [29]:
np.random.randn(10)

array([-2.59275104, -0.02751132,  0.73097352,  1.76408077, -0.12968503,
        0.64546243,  0.46195967,  0.43607044, -0.2948531 ,  1.42485905])

In [30]:
np.random.randn(3, 4)

array([[-2.6440089 , -1.33716255,  0.96282939, -1.10310222],
       [-0.19502141, -2.36551333, -0.05999981,  0.12535828],
       [-0.07383979,  0.44420596,  0.64613033,  0.29097553]])

In [35]:
mu = 100
sigma = 30

sigma * np.random.randn(20) + mu

array([ 85.88187559,  80.05571862,  70.51551911,  74.16206115,
        87.71741386, 111.88393039,  96.21669115, 124.0265765 ,
        96.63999616, 125.1785091 ,  66.39529838,  79.03789882,
       140.51852901, 129.49334501, 102.12419805,  71.7530125 ,
        61.085733  , 110.45457289, 129.12747273,  67.07671183])

In [36]:
print('np.zeros(3)    == {}'.format(np.zeros(3)))
print('np.ones(3)     == {}'.format(np.ones(3)))
print('np.full(3, 17) == {}'.format(np.full(3, 17)))

np.zeros(3)    == [0. 0. 0.]
np.ones(3)     == [1. 1. 1.]
np.full(3, 17) == [17 17 17]


In [37]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(1, 4)

array([1, 2, 3])

In [41]:
np.arange(1, 8, 2)

array([1, 3, 5, 7])

In [42]:
np.arange(3, 5, 0.5)

array([3. , 3.5, 4. , 4.5])

In [43]:
print('min: 1, max: 4, length = 4 -- {}'.format(np.linspace(1, 4, 4)))
print('min: 1, max: 4, length = 7 -- {} '.format(np.linspace(1, 4, 7)))

min: 1, max: 4, length = 4 -- [1. 2. 3. 4.]
min: 1, max: 4, length = 7 -- [1.  1.5 2.  2.5 3.  3.5 4. ] 


In [44]:
a = np.array([1, 2, 3, 4, 5])

In [45]:
a.min()

1

In [46]:
a.max()

5

In [47]:
a.mean()

3.0

In [48]:
a.sum()

15

In [49]:
a.std()

1.4142135623730951