In [2]:
import numpy as np

In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [43]:
# 1. How many negative numbers are there?
a[a < 0].size

4

In [44]:
# 2. How many positive numbers are there?
a[a > 0].size

5

In [46]:
# 3. How many even positive numbers are there?
a[(a % 2 == 0) & (a > 0)].size

3

In [7]:
# 4. If you were to add 3 to each data point, how many positive numbers would there be?
plus_three = a + 3
(plus_three > 0).sum()

10

In [18]:
a = (a + 3)
a


array([13, 19, 21, 32,  7,  8,  9,  9,  9,  3, 12,  2])

In [13]:
b = np.array([7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, 10])
b

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, 10])

In [39]:
d = b[(b % 2 == 0) & (b > 0)]
d

array([26,  2,  6, 10])

In [40]:
b ** 2

array([ 49, 169, 225, 676,   1,   4,   9,   9,   9,   9,  36, 100])

In [41]:
mu = 100
sigma = 30

sigma * b + mu

array([310, 490, 550, 880, 130, 160, 190, 190, 190,  10, 280, 400])